MusicStoreManager/urls.py
from django.urls import path
from MusicStoreManager import views
from .views import AddMelodyView

urlpatterns = [
    path('', views.HomeViewTemplate.as_view (), name='home'),
    path('albert/', views.AlbertViewTemplate.as_view (), name='albert'),
    path('bb/', views.BBViewTemplate.as_view(), name='bb'),
    path('beth/', views.BethViewTemplate.as_view(), name='beth'),
    path('buddy/', views.BuddyViewTemplate.as_view(), name='buddy'),
    path('christone/', views.ChristoneViewTemplate.as_view(), name='christone'),
    path('eric/', views.EricViewTemplate.as_view(), name='eric'),
    path('howtoplay/', views.HowToPlayViewTemplate.as_view(), name='howtoplay'),
    path('joe/', views.JoeViewTemplate.as_view(), name='joe'),
    path('srv/', views.SRVViewTemplate.as_view(), name='srv'),
    path('susan/', views.SusanViewTemplate.as_view (), name='susan'),

    path ('melody/<int:music_id>/like/', views.LikeMusicView.as_view (), name='like_music'),
    path ('recommendations/', views.RecommendMusicView.as_view (), name='recommend_music'),
    path('add-melody/', AddMelodyView.as_view(), name='add_melody'),

]

Users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from Users import views
from Users.views import CustomPasswordResetConfirmView, CustomPasswordResetCompleteView, CustomPasswordResetDoneView, \
    CustomPasswordResetView, CustomLogoutView

urlpatterns = [
    path('create_user/', views.UserCreateView.as_view(), name='create-user'),
    path('login/', auth_views.LoginView.as_view(form_class='AuthenticationNewForm'), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path ('password_reset', CustomPasswordResetView.as_view (), name='password_reset'),
    path ('password_reset/done/', CustomPasswordResetDoneView.as_view (), name='password_reset_done'),
    path ('password_reset/complete/', CustomPasswordResetCompleteView.as_view (), name='password_reset_complete'),
    path ('password_reset_confirm/', CustomPasswordResetConfirmView.as_view (),
          name='password_reset_confirm'),
]

finalproject/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from Users.forms import AuthentificationNewForm
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('recommendation/', include('RecommendationSystem.urls')),
    path('', include ('MusicStoreManager.urls')),

    path('login/', views.LoginView.as_view(form_class=AuthentificationNewForm), name='login'),
    path('', include ('django.contrib.auth.urls')),
    path('', include ('Users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MusicStoreManager/models.py
from django.db import models

class MelodiesToLearn(models.Model):
    STYLE_CHOICES = [
        ('BL', 'Blues'),
        ('BR', 'Blues Rock'),
        ('JZ', 'Jazz'),
        ('PP', 'Pop'),
    ]

    name = models.CharField(max_length=100)
    style = models.CharField(
        max_length=2,
        choices=STYLE_CHOICES,
        default='BL',
    )

    def __str__(self):
        return f'{self.name} - {self.get_style_display()}'

class Music(models.Model):
    title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title} by {self.artist}'

class User(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    favorite_melodies = models.ManyToManyField(MelodiesToLearn, related_name='fans')

    def __str__(self):
        return self.name

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    music = models.ForeignKey(Music, on_delete=models.CASCADE)
    liked_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'music')

    def __str__(self):
        return f'{self.user.name} liked {self.music.title}'

MusicStoreManager/forms.py
from django import forms
from .models import MelodiesToLearn

class MelodiesToLearnForm(forms.ModelForm):
    class Meta:
        model = MelodiesToLearn
        fields = ['name', 'style']

MusicStoreManager/views.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.db.models import Count
from .models import Music, Like
from .models import MelodiesToLearn
from .forms import MelodiesToLearnForm

class HomeViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/home.html'


class AlbertViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/albert.html'


class BBViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/bb.html'


class BethViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/beth.html'


class BuddyViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/buddy.html'


class ChristoneViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/christone.html'


class EricViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/eric.html'


class HowToPlayViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/howtoplay.html'


class JoeViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/joe.html'


class SRVViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/srv.html'


class SusanViewTemplate (TemplateView):
    template_name = 'MusicStoreManager/susan.html'


@method_decorator (login_required, name='dispatch')
class LikeMusicView (View):
    def post(self, request, music_id):
        music = get_object_or_404 (Music, id=music_id)
        like, created = Like.objects.get_or_create (user=request.user, music=music)
        if not created:
            like.count += 1
        like.save ()
        return redirect ('music_detail', music_id=music.id)


@method_decorator (login_required, name='dispatch')
class RecommendMusicView (View):
    def get(self, request):
        user_likes = Like.objects.filter (user=request.user)
        user_music_ids = user_likes.values_list ('music_id', flat=True)

        # Find other users who liked the same music
        similar_users = Like.objects.filter (music_id__in=user_music_ids).exclude (user=request.user)

        # Collaborative filtering recommendation system
        recommended_music = (Music.objects
                             .filter (like__in=similar_users)
                             .annotate (num_likes=Count ('like'))
                             .order_by ('-num_likes')
                             .exclude (id__in=user_music_ids))

        return render (request, 'recommendations.html', {'recommended_music': recommended_music})

class AddMelodyView(View):
    def get(self, request):
        form = MelodiesToLearnForm()
        return render(request, 'MusicStoreManager/add_melody.html', {'form': form})

    def post(self, request):
        form = MelodiesToLearnForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
        return render(request, 'MusicStoreManager/add_melody.html', {'form': form})

templates/MusicStoreManager/add_melody.html
{% extends 'base.html' %}

{% block content %}
  <h2>Add a New Melody</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Melody</button>
  </form>
{% endblock %}

templates/MusicStoreManager/albert.html
{% extends 'Users/../base.html' %}

{% block title %} Albert King {% endblock %}

{% block content %}


{% endblock %}

templates/MusicStoreManager/bb.html
{% extends 'Users/../base.html' %}

{% block title %} BB King {% endblock %}

{% block content %}
   
{% endblock %}

templates/MusicStoreManager/beth.html
{% extends 'Users/../base.html' %}

{% block title %} Beth Hart {% endblock %}

{% block content %} 
    
    
{% endblock %}

templates/MusicStoreManager/buddy.html
{% extends 'Users/../base.html' %}

{% block title %} Buddy Guy {% endblock %}

{% block content %} 
    
    
{% endblock %}

templates/MusicStoreManager/christone.html
{% extends 'Users/../base.html' %}

{% block title %} Christone "Kingfish" Ingram {% endblock %}

{% block content %} 
    
    
{% endblock %}

templates/MusicStoreManager/eric.html
{% extends 'Users/../base.html' %}

{% block title %} Eric Clapton {% endblock %}

{% block content %} 
    
    
{% endblock %}

templates/MusicStoreManager/home.html
{% extends 'Users/../base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
    <br><br><br>
{% for melody in melodies %}
    <div>
        <h3>{{ melody.name }} - {{ melody.get_style_display }}</h3>
        <form method="POST" action="{% url 'like-melody' melody.pk %}">
            {% csrf_token %}
            <button type="submit">Like</button>
        </form>
        <p>Likes: {{ melody.like_set.count }}</p>
    </div>
{% endfor %}
{% endblock %}

templates/MusicStoreManager/howtoplay.html
{% extends 'Users/../base.html' %}

{% block title %} How to play in the style of {% endblock %}

{% block content %} 
    
    
{% endblock %}

templates/MusicStoreManager/joe.html
{% extends 'Users/../base.html' %}

{% block title %} Joe Bonamassa {% endblock %}

{% block content %} 
    
    
{% endblock %}

templates/MusicStoreManager/srv.html
{% extends 'Users/../base.html' %}

{% block title %} Stephen Ray Vaughan {% endblock %}

{% block content %} 
    
    
{% endblock %}

templates/MusicStoreManager/susan.html
{% extends 'Users/../base.html' %}

{% block title %} Susan Tedeschi {% endblock %}

{% block content %} 
    
    
{% endblock %}